package my.DBProj;

import java.sql.*;
import java.util.*;
import javax.swing.*;
/**
 *
 * @authors Brandon Dimaya, Anne Bone, Tristan Honda
 */
public class DBProjUI extends javax.swing.JFrame {
    
    static Connection connect;
    static Statement statement;
    ResultSet rs;
    
    /**
     * Creates new form DBProjUI
     */
    public DBProjUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AllRestaurants = new javax.swing.JFrame();
        AllRestaurantsPanel = new javax.swing.JPanel();
        AllRestaurantsRests = new javax.swing.JComboBox();
        AllRestaurantsLabel = new javax.swing.JLabel();
        AllAddressLabel = new javax.swing.JLabel();
        AllPhoneLabel = new javax.swing.JLabel();
        AllRatingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllAddressPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllPhonePane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        AllRatingPane = new javax.swing.JTextPane();
        AllRestaurantsBackButton = new javax.swing.JButton();
        RestaurantMenus = new javax.swing.JFrame();
        RestaurantMenusPanel = new javax.swing.JPanel();
        RestaurantMenusLabel = new javax.swing.JLabel();
        RestaurantMenusRests = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        RestaurantMenusPane = new javax.swing.JTextPane();
        RestaurantMenusBackButton = new javax.swing.JButton();
        ReviewsByRestaurant = new javax.swing.JFrame();
        ReviewsByRestPanel = new javax.swing.JPanel();
        ReviewsByRestLabel = new javax.swing.JLabel();
        ReviewsByRestRests = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReviewsByRestPane = new javax.swing.JTextPane();
        ReviewsByRestBackButton = new javax.swing.JButton();
        ReviewsByUser = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        ReviewsByUserLabel = new javax.swing.JLabel();
        ReviewsByUserUsername = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        ReviewsByUserPane = new javax.swing.JTextPane();
        ReviewByUserBackButton = new javax.swing.JButton();
        MakeOrder = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        MakeOrderRestLabel = new javax.swing.JLabel();
        MakeOrderRests = new javax.swing.JComboBox();
        MakeOrderMenuLabel = new javax.swing.JLabel();
        MakeOrderMenu = new javax.swing.JComboBox();
        MakeOrderUsernameLabel = new javax.swing.JLabel();
        MakeOrderUsername = new javax.swing.JTextField();
        MakeOrderPriceLabel = new javax.swing.JLabel();
        MakeOrderPrice = new javax.swing.JLabel();
        MakeOrderCompleteButton = new javax.swing.JButton();
        MakeOrderCancelButton = new javax.swing.JButton();
        AddRestaurant = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        AddRestNameLabel = new javax.swing.JLabel();
        AddRestName = new javax.swing.JTextField();
        AddRestAddressLabel = new javax.swing.JLabel();
        AddRestAddress = new javax.swing.JTextField();
        AddRestPhoneLabel = new javax.swing.JLabel();
        AddRestPhone = new javax.swing.JTextField();
        AddRestAddButton = new javax.swing.JButton();
        AddRestCancelButton = new javax.swing.JButton();
        AddItem = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        AddItemRestLabel = new javax.swing.JLabel();
        AddItemRest = new javax.swing.JComboBox();
        AddItemNameLabel = new javax.swing.JLabel();
        AddItemName = new javax.swing.JTextField();
        AddItemPriceLabel = new javax.swing.JLabel();
        AddItemPrice = new javax.swing.JTextField();
        AddItemTypeLabel = new javax.swing.JLabel();
        AddItemType = new javax.swing.JTextField();
        AddItemDescLabel = new javax.swing.JLabel();
        AddItemDesc = new javax.swing.JTextField();
        AddItemAddButton = new javax.swing.JButton();
        AddItemCancelButton = new javax.swing.JButton();
        AddReview = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        AddReviewRestLabel = new javax.swing.JLabel();
        AddReviewRest = new javax.swing.JComboBox();
        AddReviewRevLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        AddReviewRev = new javax.swing.JTextArea();
        AddReviewRatingLabel = new javax.swing.JLabel();
        AddReviewRating = new javax.swing.JTextField();
        AddReviewNameLabel = new javax.swing.JLabel();
        AddReviewName = new javax.swing.JTextField();
        AddReviewSubmitButton = new javax.swing.JButton();
        AddReviewCancelButton = new javax.swing.JButton();
        mainPane = new javax.swing.JTabbedPane();
        RestsTab = new javax.swing.JPanel();
        AllRestaurantsButton = new javax.swing.JButton();
        ReviewByRestsButton = new javax.swing.JButton();
        RestsMenusButton = new javax.swing.JButton();
        ReviewByUsersButton = new javax.swing.JButton();
        MakeOrderButton = new javax.swing.JButton();
        UpdatesTab = new javax.swing.JPanel();
        AddRestsButton = new javax.swing.JButton();
        AddMenuItemButton = new javax.swing.JButton();
        AddReviewButton = new javax.swing.JButton();

        AllRestaurantsRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        AllRestaurantsRests.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UpdateDetailsHandler(evt);
            }
        });
        AllRestaurantsRests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRestaurantsRestsActionPerformed(evt);
            }
        });

        AllRestaurantsLabel.setText("Select the restaurant you'd like to view details for:");

        AllAddressLabel.setText("Address: ");

        AllPhoneLabel.setText("Phone Number: ");

        AllRatingLabel.setText("Rating: ");

        AllAddressPane.setEditable(false);
        AllAddressPane.setText(GetRestaurantAddress(GetRestaurantNames()[0]));
        jScrollPane1.setViewportView(AllAddressPane);

        AllPhonePane.setText(GetRestaurantPhone(GetRestaurantNames()[0]));
        jScrollPane2.setViewportView(AllPhonePane);

        AllRatingPane.setText(GetRestaurantRating(GetRestaurantNames()[0]));
        jScrollPane3.setViewportView(AllRatingPane);

        AllRestaurantsBackButton.setText("Back");
        AllRestaurantsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRestaurantsBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllRestaurantsPanelLayout = new javax.swing.GroupLayout(AllRestaurantsPanel);
        AllRestaurantsPanel.setLayout(AllRestaurantsPanelLayout);
        AllRestaurantsPanelLayout.setHorizontalGroup(
            AllRestaurantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllRestaurantsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AllRestaurantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AllRestaurantsLabel)
                    .addComponent(AllRestaurantsRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllAddressLabel)
                    .addComponent(AllPhoneLabel)
                    .addComponent(AllRatingLabel)
                    .addGroup(AllRestaurantsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(AllRestaurantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllRestaurantsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AllRestaurantsBackButton)
                .addContainerGap())
        );
        AllRestaurantsPanelLayout.setVerticalGroup(
            AllRestaurantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllRestaurantsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AllRestaurantsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllRestaurantsRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AllAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(AllPhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(AllRatingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AllRestaurantsBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AllRestaurantsLayout = new javax.swing.GroupLayout(AllRestaurants.getContentPane());
        AllRestaurants.getContentPane().setLayout(AllRestaurantsLayout);
        AllRestaurantsLayout.setHorizontalGroup(
            AllRestaurantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllRestaurantsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AllRestaurantsLayout.setVerticalGroup(
            AllRestaurantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllRestaurantsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RestaurantMenusLabel.setText("Select the restaurant you'd like to view the menu for:");

        RestaurantMenusRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        RestaurantMenusRests.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RestaurantMenusRestsItemStateChanged(evt);
            }
        });

        RestaurantMenusPane.setEditable(false);
        RestaurantMenusPane.setText(GetRestaurantMenu(GetRestaurantNames()[0]));
        jScrollPane4.setViewportView(RestaurantMenusPane);

        RestaurantMenusBackButton.setText("Back");
        RestaurantMenusBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantMenusBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RestaurantMenusPanelLayout = new javax.swing.GroupLayout(RestaurantMenusPanel);
        RestaurantMenusPanel.setLayout(RestaurantMenusPanelLayout);
        RestaurantMenusPanelLayout.setHorizontalGroup(
            RestaurantMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestaurantMenusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RestaurantMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantMenusLabel)
                    .addComponent(RestaurantMenusRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RestaurantMenusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RestaurantMenusBackButton)
                .addContainerGap())
        );
        RestaurantMenusPanelLayout.setVerticalGroup(
            RestaurantMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestaurantMenusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RestaurantMenusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RestaurantMenusRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(RestaurantMenusBackButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout RestaurantMenusLayout = new javax.swing.GroupLayout(RestaurantMenus.getContentPane());
        RestaurantMenus.getContentPane().setLayout(RestaurantMenusLayout);
        RestaurantMenusLayout.setHorizontalGroup(
            RestaurantMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RestaurantMenusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RestaurantMenusLayout.setVerticalGroup(
            RestaurantMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RestaurantMenusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ReviewsByRestLabel.setText("Select which restaurant you'd like to see reviews for:");

        ReviewsByRestRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        ReviewsByRestRests.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReviewsByRestRestsItemStateChanged(evt);
            }
        });

        ReviewsByRestPane.setEditable(false);
        ReviewsByRestPane.setText(GetRestaurantReviews(GetRestaurantNames()[0]));
        jScrollPane5.setViewportView(ReviewsByRestPane);

        ReviewsByRestBackButton.setText("Back");
        ReviewsByRestBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewsByRestBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReviewsByRestPanelLayout = new javax.swing.GroupLayout(ReviewsByRestPanel);
        ReviewsByRestPanel.setLayout(ReviewsByRestPanelLayout);
        ReviewsByRestPanelLayout.setHorizontalGroup(
            ReviewsByRestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewsByRestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReviewsByRestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReviewsByRestLabel)
                    .addComponent(ReviewsByRestRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReviewsByRestPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReviewsByRestBackButton)
                .addContainerGap())
        );
        ReviewsByRestPanelLayout.setVerticalGroup(
            ReviewsByRestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewsByRestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReviewsByRestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReviewsByRestRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReviewsByRestBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReviewsByRestaurantLayout = new javax.swing.GroupLayout(ReviewsByRestaurant.getContentPane());
        ReviewsByRestaurant.getContentPane().setLayout(ReviewsByRestaurantLayout);
        ReviewsByRestaurantLayout.setHorizontalGroup(
            ReviewsByRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReviewsByRestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReviewsByRestaurantLayout.setVerticalGroup(
            ReviewsByRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReviewsByRestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ReviewsByUserLabel.setText("Enter the username of the user you'd like to see reviews from:");

        ReviewsByUserUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewsByUserUsernameActionPerformed(evt);
            }
        });

        ReviewsByUserPane.setEditable(false);
        jScrollPane6.setViewportView(ReviewsByUserPane);

        ReviewByUserBackButton.setText("Back");
        ReviewByUserBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewByUserBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReviewsByUserLabel)
                    .addComponent(ReviewsByUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReviewByUserBackButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReviewsByUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReviewsByUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ReviewByUserBackButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout ReviewsByUserLayout = new javax.swing.GroupLayout(ReviewsByUser.getContentPane());
        ReviewsByUser.getContentPane().setLayout(ReviewsByUserLayout);
        ReviewsByUserLayout.setHorizontalGroup(
            ReviewsByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReviewsByUserLayout.setVerticalGroup(
            ReviewsByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MakeOrderRestLabel.setText("Select the restaurant you'd like to make the order to:");

        MakeOrderRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        MakeOrderRests.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MakeOrderRestsItemStateChanged(evt);
            }
        });

        MakeOrderMenuLabel.setText("Select the item from the menu you'd like to order:");

        MakeOrderMenu.setModel(new javax.swing.DefaultComboBoxModel(GetDishNames(GetRestaurantNames()[0])));
        MakeOrderMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MakeOrderMenuItemStateChanged(evt);
            }
        });

        MakeOrderUsernameLabel.setText("Enter your username:");

        MakeOrderPriceLabel.setText("The price will be:");

        MakeOrderPrice.setText("$" + GetDishPrice(MakeOrderMenu.getSelectedItem().toString()));

        MakeOrderCompleteButton.setText("Complete Order");
        MakeOrderCompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeOrderCompleteButtonActionPerformed(evt);
            }
        });

        MakeOrderCancelButton.setText("Cancel Order");
        MakeOrderCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeOrderCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MakeOrderRestLabel)
                            .addComponent(MakeOrderRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeOrderMenuLabel)
                            .addComponent(MakeOrderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeOrderUsernameLabel)
                            .addComponent(MakeOrderUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeOrderPriceLabel)
                            .addComponent(MakeOrderPrice)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(MakeOrderCompleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(MakeOrderCancelButton)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeOrderRestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeOrderRests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MakeOrderMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeOrderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MakeOrderUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeOrderUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MakeOrderPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeOrderPrice)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeOrderCompleteButton)
                    .addComponent(MakeOrderCancelButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MakeOrderLayout = new javax.swing.GroupLayout(MakeOrder.getContentPane());
        MakeOrder.getContentPane().setLayout(MakeOrderLayout);
        MakeOrderLayout.setHorizontalGroup(
            MakeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MakeOrderLayout.setVerticalGroup(
            MakeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddRestNameLabel.setText("Enter the restaurant name:");

        AddRestAddressLabel.setText("Enter the restaurant address:");

        AddRestPhoneLabel.setText("Enter the restaurant phone number:");

        AddRestAddButton.setText("Add Restaurant");
        AddRestAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRestAddButtonActionPerformed(evt);
            }
        });

        AddRestCancelButton.setText("Cancel");
        AddRestCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRestCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddRestNameLabel)
                            .addComponent(AddRestName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddRestAddressLabel)
                            .addComponent(AddRestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddRestPhoneLabel)
                            .addComponent(AddRestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(AddRestAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddRestCancelButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddRestNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddRestAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddRestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddRestPhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddRestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRestAddButton)
                    .addComponent(AddRestCancelButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout AddRestaurantLayout = new javax.swing.GroupLayout(AddRestaurant.getContentPane());
        AddRestaurant.getContentPane().setLayout(AddRestaurantLayout);
        AddRestaurantLayout.setHorizontalGroup(
            AddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddRestaurantLayout.setVerticalGroup(
            AddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddItemRestLabel.setText("Select the restaurant you'd like to add a menu item for:");

        AddItemRest.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));

        AddItemNameLabel.setText("Enter the dish name:");

        AddItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemNameActionPerformed(evt);
            }
        });

        AddItemPriceLabel.setText("Enter the dish price:");

        AddItemTypeLabel.setText("What type of dish?");

        AddItemDescLabel.setText("Enter short description of the dish:");

        AddItemAddButton.setText("Add Item");
        AddItemAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemAddButtonActionPerformed(evt);
            }
        });

        AddItemCancelButton.setText("Cancel");
        AddItemCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddItemDesc)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddItemRestLabel)
                            .addComponent(AddItemRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddItemNameLabel)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AddItemPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddItemPriceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AddItemTypeLabel)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AddItemType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(AddItemName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(AddItemDescLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(AddItemAddButton)
                .addGap(55, 55, 55)
                .addComponent(AddItemCancelButton)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddItemRestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddItemRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddItemNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddItemPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddItemTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddItemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddItemDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItemAddButton)
                    .addComponent(AddItemCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AddItemLayout = new javax.swing.GroupLayout(AddItem.getContentPane());
        AddItem.getContentPane().setLayout(AddItemLayout);
        AddItemLayout.setHorizontalGroup(
            AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddItemLayout.setVerticalGroup(
            AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddReviewRestLabel.setText("Select the restaurant you'd like to leave a review for:");

        AddReviewRest.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));

        AddReviewRevLabel.setText("Write your review:");

        AddReviewRev.setColumns(20);
        AddReviewRev.setRows(5);
        jScrollPane7.setViewportView(AddReviewRev);

        AddReviewRatingLabel.setText("What would you rate this restaurant? (1-5)");

        AddReviewNameLabel.setText("What's your username?");

        AddReviewSubmitButton.setText("Submit Review");
        AddReviewSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReviewSubmitButtonActionPerformed(evt);
            }
        });

        AddReviewCancelButton.setText("Cancel");
        AddReviewCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReviewCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddReviewRestLabel)
                            .addComponent(AddReviewRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddReviewRevLabel)
                            .addComponent(AddReviewRatingLabel)
                            .addComponent(AddReviewRating, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddReviewNameLabel)
                            .addComponent(AddReviewName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(AddReviewSubmitButton)
                        .addGap(26, 26, 26)
                        .addComponent(AddReviewCancelButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddReviewRestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddReviewRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddReviewRevLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddReviewRatingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddReviewRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddReviewNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddReviewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddReviewSubmitButton)
                    .addComponent(AddReviewCancelButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AddReviewLayout = new javax.swing.GroupLayout(AddReview.getContentPane());
        AddReview.getContentPane().setLayout(AddReviewLayout);
        AddReviewLayout.setHorizontalGroup(
            AddReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddReviewLayout.setVerticalGroup(
            AddReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AllRestaurantsButton.setText("All Restaurants");
        AllRestaurantsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRestaurantsButtonActionPerformed(evt);
            }
        });

        ReviewByRestsButton.setText("Reviews by Restaurant");
        ReviewByRestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewByRestsButtonActionPerformed(evt);
            }
        });

        RestsMenusButton.setText("Restaurant Menus");
        RestsMenusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestsMenusButtonActionPerformed(evt);
            }
        });

        ReviewByUsersButton.setText("Reviews by User");
        ReviewByUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewByUsersButtonActionPerformed(evt);
            }
        });

        MakeOrderButton.setText("Make an order");
        MakeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RestsTabLayout = new javax.swing.GroupLayout(RestsTab);
        RestsTab.setLayout(RestsTabLayout);
        RestsTabLayout.setHorizontalGroup(
            RestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestsTabLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(RestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReviewByUsersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReviewByRestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RestsMenusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllRestaurantsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MakeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        RestsTabLayout.setVerticalGroup(
            RestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestsTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AllRestaurantsButton)
                .addGap(27, 27, 27)
                .addComponent(RestsMenusButton)
                .addGap(29, 29, 29)
                .addComponent(ReviewByRestsButton)
                .addGap(28, 28, 28)
                .addComponent(ReviewByUsersButton)
                .addGap(30, 30, 30)
                .addComponent(MakeOrderButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        mainPane.addTab("Restaurants", RestsTab);

        AddRestsButton.setText("Add Restaurant");
        AddRestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRestsButtonActionPerformed(evt);
            }
        });

        AddMenuItemButton.setText("Add Menu Item");
        AddMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMenuItemButtonActionPerformed(evt);
            }
        });

        AddReviewButton.setText("Add Review");
        AddReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatesTabLayout = new javax.swing.GroupLayout(UpdatesTab);
        UpdatesTab.setLayout(UpdatesTabLayout);
        UpdatesTabLayout.setHorizontalGroup(
            UpdatesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatesTabLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(UpdatesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddMenuItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddReviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddRestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        UpdatesTabLayout.setVerticalGroup(
            UpdatesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatesTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(AddRestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(AddMenuItemButton)
                .addGap(62, 62, 62)
                .addComponent(AddReviewButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        mainPane.addTab("Updates", UpdatesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRestsButtonActionPerformed
        AddRestaurant.pack();
        AddRestaurant.setLocationRelativeTo(null);
        AddRestaurant.revalidate();
        AddRestaurant.repaint();
        AddRestaurant.setVisible(true);
    }//GEN-LAST:event_AddRestsButtonActionPerformed

    private void AddMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMenuItemButtonActionPerformed
        AddItemRest.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        AddItem.pack();
        AddItem.setLocationRelativeTo(null);
        AddItem.revalidate();
        AddItem.repaint();
        AddItem.setVisible(true);
    }//GEN-LAST:event_AddMenuItemButtonActionPerformed

    private void AddReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReviewButtonActionPerformed
        AddReviewRest.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        AddReview.pack();
        AddReview.setLocationRelativeTo(null);
        AddReview.revalidate();
        AddReview.repaint();
        AddReview.setVisible(true);
    }//GEN-LAST:event_AddReviewButtonActionPerformed

    private void AllRestaurantsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRestaurantsButtonActionPerformed
        AllRestaurantsRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        AllAddressPane.setText(GetRestaurantAddress(GetRestaurantNames()[0]));
        AllPhonePane.setText(GetRestaurantPhone(GetRestaurantNames()[0]));
        AllRatingPane.setText(GetRestaurantRating(GetRestaurantNames()[0]));
        AllRestaurants.pack();
        AllRestaurants.setLocationRelativeTo(null);
        AllRestaurants.revalidate();
        AllRestaurants.repaint();
        AllRestaurants.setVisible(true);
    }//GEN-LAST:event_AllRestaurantsButtonActionPerformed

    private void UpdateDetailsHandler(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UpdateDetailsHandler
        AllAddressPane.setText(GetRestaurantAddress(evt.getItem().toString()));
        AllPhonePane.setText(GetRestaurantPhone(evt.getItem().toString()));
        AllRatingPane.setText(GetRestaurantRating(evt.getItem().toString()));
    }//GEN-LAST:event_UpdateDetailsHandler

    private void AllRestaurantsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRestaurantsBackButtonActionPerformed
        AllRestaurants.setVisible(false);
    }//GEN-LAST:event_AllRestaurantsBackButtonActionPerformed

    private void AllRestaurantsRestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRestaurantsRestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllRestaurantsRestsActionPerformed

    private void RestsMenusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestsMenusButtonActionPerformed
        RestaurantMenusRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        RestaurantMenusPane.setText(GetRestaurantMenu(GetRestaurantNames()[0]));
        RestaurantMenus.pack();
        RestaurantMenus.setLocationRelativeTo(null);
        RestaurantMenus.revalidate();
        RestaurantMenus.repaint();
        RestaurantMenus.setVisible(true);
    }//GEN-LAST:event_RestsMenusButtonActionPerformed

    private void RestaurantMenusBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantMenusBackButtonActionPerformed
        RestaurantMenus.setVisible(false);
    }//GEN-LAST:event_RestaurantMenusBackButtonActionPerformed

    private void RestaurantMenusRestsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RestaurantMenusRestsItemStateChanged
        RestaurantMenusPane.setText(GetRestaurantMenu(evt.getItem().toString()));
    }//GEN-LAST:event_RestaurantMenusRestsItemStateChanged

    private void ReviewsByRestBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewsByRestBackButtonActionPerformed
        ReviewsByRestaurant.setVisible(false);
    }//GEN-LAST:event_ReviewsByRestBackButtonActionPerformed

    private void ReviewByRestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewByRestsButtonActionPerformed
        ReviewsByRestRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        ReviewsByRestPane.setText(GetRestaurantReviews(GetRestaurantNames()[0]));
        ReviewsByRestaurant.pack();
        ReviewsByRestaurant.setLocationRelativeTo(null);
        ReviewsByRestaurant.revalidate();
        ReviewsByRestaurant.repaint();
        ReviewsByRestaurant.setVisible(true);
    }//GEN-LAST:event_ReviewByRestsButtonActionPerformed

    private void ReviewsByRestRestsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReviewsByRestRestsItemStateChanged
        ReviewsByRestPane.setText(GetRestaurantReviews(evt.getItem().toString()));
    }//GEN-LAST:event_ReviewsByRestRestsItemStateChanged

    private void ReviewByUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewByUsersButtonActionPerformed
        ReviewsByUser.pack();
        ReviewsByUser.setLocationRelativeTo(null);
        ReviewsByUser.setVisible(true);
    }//GEN-LAST:event_ReviewByUsersButtonActionPerformed

    private void ReviewsByUserUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewsByUserUsernameActionPerformed
        ReviewsByUserPane.setText(GetUserReviews(ReviewsByUserUsername.getText()));
    }//GEN-LAST:event_ReviewsByUserUsernameActionPerformed

    private void ReviewByUserBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewByUserBackButtonActionPerformed
        ReviewsByUser.setVisible(false);
    }//GEN-LAST:event_ReviewByUserBackButtonActionPerformed

    private void MakeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeOrderButtonActionPerformed
        MakeOrderRests.setModel(new javax.swing.DefaultComboBoxModel(GetRestaurantNames()));
        MakeOrder.pack();
        MakeOrder.setLocationRelativeTo(null);
        MakeOrder.setVisible(true);
    }//GEN-LAST:event_MakeOrderButtonActionPerformed

    private void MakeOrderRestsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MakeOrderRestsItemStateChanged
        MakeOrderMenu.setModel(new javax.swing.DefaultComboBoxModel(GetDishNames(evt.getItem().toString())));
        MakeOrderPrice.setText("$" + GetDishPrice (GetDishNames(evt.getItem().toString())[0]));
    }//GEN-LAST:event_MakeOrderRestsItemStateChanged

    private void MakeOrderMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MakeOrderMenuItemStateChanged
        MakeOrderPrice.setText("$" + GetDishPrice(evt.getItem().toString()));
    }//GEN-LAST:event_MakeOrderMenuItemStateChanged

    private void MakeOrderCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeOrderCancelButtonActionPerformed
        MakeOrder.setVisible(false);
    }//GEN-LAST:event_MakeOrderCancelButtonActionPerformed

    private void MakeOrderCompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeOrderCompleteButtonActionPerformed
        try {
            connect.setAutoCommit(false);

                    statement.executeUpdate("insert into RestaurantTransactions "
                            + "(restaurant_id, restaurant_name, dish, price, purchase_date, customer) "
                            + "values(" + GetRestaurantID(MakeOrderRests.getSelectedItem().toString()) + ", '" + MakeOrderRests.getSelectedItem().toString() + "'" +
                            ", '" + MakeOrderMenu.getSelectedItem().toString() + "', "
                            + GetDishPrice (MakeOrderMenu.getSelectedItem().toString()) + ", now(), '" + MakeOrderUsername.getText() + "')");

                    connect.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        MakeOrder.dispose();
    }//GEN-LAST:event_MakeOrderCompleteButtonActionPerformed

    private void AddRestCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRestCancelButtonActionPerformed
        AddRestaurant.setVisible(false);
    }//GEN-LAST:event_AddRestCancelButtonActionPerformed

    private void AddRestAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRestAddButtonActionPerformed
        try {
            connect.setAutoCommit(false);

                    statement.executeUpdate("insert into Restaurants(name, address, phone_number) "
                            + "values ('" + AddRestName.getText() + "', '" + AddRestAddress.getText() + "', '" + AddRestPhone.getText() + "')");

                    connect.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        AddRestaurant.dispose();
    }//GEN-LAST:event_AddRestAddButtonActionPerformed

    private void AddItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItemNameActionPerformed

    private void AddItemAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemAddButtonActionPerformed
        try {
            connect.setAutoCommit(false);

                    statement.executeUpdate("insert into Menu(dishname, restaurant_id, price, dish_type, description, restaurant_name)"
                            + " values ('" + AddItemName.getText() + "', " + GetRestaurantID (AddItemRest.getSelectedItem().toString())
                            + ", " + Double.parseDouble(AddItemPrice.getText()) + ", '" + AddItemType.getText() + "', '"
                            + AddItemDesc.getText() + "', '" + AddItemRest.getSelectedItem().toString() + "')");

                    connect.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        AddItem.setVisible(false);
    }//GEN-LAST:event_AddItemAddButtonActionPerformed

    private void AddItemCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemCancelButtonActionPerformed
        AddItem.setVisible(false);
    }//GEN-LAST:event_AddItemCancelButtonActionPerformed

    private void AddReviewCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReviewCancelButtonActionPerformed
        AddReview.setVisible(false);
    }//GEN-LAST:event_AddReviewCancelButtonActionPerformed

    private void AddReviewSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReviewSubmitButtonActionPerformed
        try {
            connect.setAutoCommit(false);

                    statement.executeUpdate("INSERT into Reviews (review, rating, restaurant_id, username, restaurant_name)"
                            + "values ('" + AddReviewRev.getText() + "', " + Integer.parseInt(AddReviewRating.getText()) + ", " 
                            + GetRestaurantID (AddReviewRest.getSelectedItem().toString())
                            + ", '" + AddReviewName.getText() + "', '" + AddReviewRest.getSelectedItem().toString() + "')"
                    );

                    connect.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        AddReview.setVisible(false);
    }//GEN-LAST:event_AddReviewSubmitButtonActionPerformed

    private int GetRestaurantID (String name) {
        int ret = 0;
        
        try {
            rs = statement.executeQuery("select r.restaurant_id from Restaurants r where r.name = '" + name + "'");
            
            if (rs.next()) {
                ret = Integer.parseInt(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String[] GetRestaurantNames () {
        String[] names = new String[10];
        int count = 0;
        
        try {
            rs = statement.executeQuery("select count(r.name) from Restaurants r");
            
            if (rs.next()) {
                names = new String[Integer.parseInt(rs.getString(1))];
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            rs = statement.executeQuery("select r.name from Restaurants r");
        
            while (rs.next()) {
                names[count] = rs.getString(1);
                count++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return names;
    }
    
    private String[] GetDishNames (String rest) {
        String[] names = new String[10];
        int count = 0;
        
        try {
            rs = statement.executeQuery("SELECT count(Menu.dishname) "
                            + "FROM Menu JOIN Restaurants ON Menu.restaurant_id=Restaurants.restaurant_id"
                            + " where Restaurants.name='" + rest + "'");
            
            if (rs.next()) {
                names = new String[Integer.parseInt(rs.getString(1))];
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            rs = statement.executeQuery("SELECT Menu.dishname "
                            + "FROM Menu JOIN Restaurants ON Menu.restaurant_id=Restaurants.restaurant_id"
                            + " where Restaurants.name='" + rest + "'");
        
            while (rs.next()) {
                names[count] = rs.getString(1);
                count++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return names;
        
    }
    
    private double GetDishPrice (String dish) {
        double price = 0.0;
        
        try {
            rs = statement.executeQuery("select m.price from Menu m where dishname='"
                            + dish + "'");

            // this stores the price of the selected dish automatically
            if (rs.next()) {
                price = Double.parseDouble(rs.getString(1));
            } else {
                price = 0.0;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return price;
    }
    
    private String GetRestaurantAddress (String name) {
        String ret = "";
        
        try {
            rs = statement.executeQuery("select r.address from Restaurants r where r.name = '" + name + "'");
            
            if (rs.next()) {
                ret = rs.getString(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String GetRestaurantPhone (String name) {
        String ret = "";
        
        try {
            rs = statement.executeQuery("select r.phone_number from Restaurants r where r.name = '" + name + "'");
            
            if (rs.next()) {
                ret = rs.getString(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String GetRestaurantRating (String name) {
        String ret = "";
        
        try {
            rs = statement.executeQuery("select r.rating from Restaurants r where r.name = '" + name + "'");
            
            if (rs.next()) {
                ret = rs.getString(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String GetRestaurantMenu (String name) {
        String ret = "";
        int count = 1;
        
        try {
            rs = statement.executeQuery("SELECT Menu.dishname, Menu.price, Menu.dish_type, Menu.description "
                            + "FROM Menu JOIN Restaurants ON Menu.restaurant_id=Restaurants.restaurant_id"
                            + " where Restaurants.name='" + name + "'");
            
                    while (rs.next()) {
                        ret = ret.concat("Item " + count + ":\n");
                        ret = ret.concat("Dishname: " + rs.getString(1) + "\n");
                        ret = ret.concat("Price: " + rs.getString(2) + "\n");
                        ret = ret.concat("Type: " + rs.getString(3) + "\n");
                        ret = ret.concat("Description: " + rs.getString(4) + "\n");
                        ret = ret.concat("\n \n");
                        count++;
                    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String GetRestaurantReviews (String name) {
        String ret = "";
        int count = 1;
        
        try {
            rs = statement.executeQuery("SELECT Reviews.review, Reviews.rating, Reviews.username "
                            + "FROM Reviews JOIN Restaurants ON Reviews.restaurant_id=Restaurants.restaurant_id"
                            + " where Restaurants.name='" + name + "'");
            
                    while (rs.next()) {
                        ret = ret.concat("Review " + count + ":\n");
                        ret = ret.concat(rs.getString(1) + "\n");
                        ret = ret.concat(rs.getString(2) + " Stars by " + rs.getString(3) + "\n");
                        ret.concat("\n \n");
                        count++;
                    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    private String GetUserReviews (String username) {
        String ret = "";
        int count = 1;
        
        try {
            rs = statement.executeQuery("select r.review, r.rating, re.name"
                            + " from Restaurants re join Reviews r on re.restaurant_id=r.restaurant_id"
                            + " where r.username='" + username + "'");

            while (rs.next()) {
                ret = ret.concat("Review " + count + ":\n");
                ret = ret.concat("Review: " + rs.getString(1) + "\n");
                ret = ret.concat("Rating: " + rs.getString(2) + "\n");
                ret = ret.concat("Restaurant: " + rs.getString(3) + "\n");
                ret = ret.concat("\n \n");
                count++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return ret;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBProjUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBProjUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBProjUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBProjUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Connecting...");
            
            connect = DriverManager.getConnection("jdbc:mysql://cslvm74.csc.calpoly.edu:3306/tihonda?user=tihonda&password=8907531");
            System.out.println("Connected.");
            
            statement = connect.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBProjUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AddItem;
    private javax.swing.JButton AddItemAddButton;
    private javax.swing.JButton AddItemCancelButton;
    private javax.swing.JTextField AddItemDesc;
    private javax.swing.JLabel AddItemDescLabel;
    private javax.swing.JTextField AddItemName;
    private javax.swing.JLabel AddItemNameLabel;
    private javax.swing.JTextField AddItemPrice;
    private javax.swing.JLabel AddItemPriceLabel;
    private javax.swing.JComboBox AddItemRest;
    private javax.swing.JLabel AddItemRestLabel;
    private javax.swing.JTextField AddItemType;
    private javax.swing.JLabel AddItemTypeLabel;
    private javax.swing.JButton AddMenuItemButton;
    private javax.swing.JButton AddRestAddButton;
    private javax.swing.JTextField AddRestAddress;
    private javax.swing.JLabel AddRestAddressLabel;
    private javax.swing.JButton AddRestCancelButton;
    private javax.swing.JTextField AddRestName;
    private javax.swing.JLabel AddRestNameLabel;
    private javax.swing.JTextField AddRestPhone;
    private javax.swing.JLabel AddRestPhoneLabel;
    private javax.swing.JFrame AddRestaurant;
    private javax.swing.JButton AddRestsButton;
    private javax.swing.JFrame AddReview;
    private javax.swing.JButton AddReviewButton;
    private javax.swing.JButton AddReviewCancelButton;
    private javax.swing.JTextField AddReviewName;
    private javax.swing.JLabel AddReviewNameLabel;
    private javax.swing.JTextField AddReviewRating;
    private javax.swing.JLabel AddReviewRatingLabel;
    private javax.swing.JComboBox AddReviewRest;
    private javax.swing.JLabel AddReviewRestLabel;
    private javax.swing.JTextArea AddReviewRev;
    private javax.swing.JLabel AddReviewRevLabel;
    private javax.swing.JButton AddReviewSubmitButton;
    private javax.swing.JLabel AllAddressLabel;
    private javax.swing.JTextPane AllAddressPane;
    private javax.swing.JLabel AllPhoneLabel;
    private javax.swing.JTextPane AllPhonePane;
    private javax.swing.JLabel AllRatingLabel;
    private javax.swing.JTextPane AllRatingPane;
    private javax.swing.JFrame AllRestaurants;
    private javax.swing.JButton AllRestaurantsBackButton;
    private javax.swing.JButton AllRestaurantsButton;
    private javax.swing.JLabel AllRestaurantsLabel;
    private javax.swing.JPanel AllRestaurantsPanel;
    private javax.swing.JComboBox AllRestaurantsRests;
    private javax.swing.JFrame MakeOrder;
    private javax.swing.JButton MakeOrderButton;
    private javax.swing.JButton MakeOrderCancelButton;
    private javax.swing.JButton MakeOrderCompleteButton;
    private javax.swing.JComboBox MakeOrderMenu;
    private javax.swing.JLabel MakeOrderMenuLabel;
    private javax.swing.JLabel MakeOrderPrice;
    private javax.swing.JLabel MakeOrderPriceLabel;
    private javax.swing.JLabel MakeOrderRestLabel;
    private javax.swing.JComboBox MakeOrderRests;
    private javax.swing.JTextField MakeOrderUsername;
    private javax.swing.JLabel MakeOrderUsernameLabel;
    private javax.swing.JFrame RestaurantMenus;
    private javax.swing.JButton RestaurantMenusBackButton;
    private javax.swing.JLabel RestaurantMenusLabel;
    private javax.swing.JTextPane RestaurantMenusPane;
    private javax.swing.JPanel RestaurantMenusPanel;
    private javax.swing.JComboBox RestaurantMenusRests;
    private javax.swing.JButton RestsMenusButton;
    private javax.swing.JPanel RestsTab;
    private javax.swing.JButton ReviewByRestsButton;
    private javax.swing.JButton ReviewByUserBackButton;
    private javax.swing.JButton ReviewByUsersButton;
    private javax.swing.JButton ReviewsByRestBackButton;
    private javax.swing.JLabel ReviewsByRestLabel;
    private javax.swing.JTextPane ReviewsByRestPane;
    private javax.swing.JPanel ReviewsByRestPanel;
    private javax.swing.JComboBox ReviewsByRestRests;
    private javax.swing.JFrame ReviewsByRestaurant;
    private javax.swing.JFrame ReviewsByUser;
    private javax.swing.JLabel ReviewsByUserLabel;
    private javax.swing.JTextPane ReviewsByUserPane;
    private javax.swing.JTextField ReviewsByUserUsername;
    private javax.swing.JPanel UpdatesTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane mainPane;
    // End of variables declaration//GEN-END:variables
}
